put http://localhost:3001/api/auth/user-details
Content-Type: application/json

{
  "email": "melxi@mail.com",
  "firstName": "Muhammad",
  "lastName": "Melxi",
  "phone": "0440240486",
  "address": "Leikosaarentie 3 A 19",
  "index": "00900",
  "city": "Helsinki"
}